### ISSUE TITLE
架构设计

### ISSUE THREAD

**Issue by miscdec** [liushu-project/liushu#31]
你好，我在搜索时发现了这个项目，感觉有点意思，本人正好也在思考下一代输入法平台应该如何设计。想问下作者对于这个项目准备如何设计这个套件的架构呢？是准备做成类型安全的rime吗？不同平台的通信协议不同，组件之间该如何通信呢？

**Comment by Eliot00** [comment]
目前还只是专注在Android平台的实现上，没有什么架构上的想法，欢迎提Issue或PR
